### ISSUE TITLE
Overlay phasor cluster id layer with summed intensity image

### ISSUE THREAD

**Issue by cwetzker** [zoccoler/napari-flim-phasor-plotter#36]
hi @zoccoler & @sviaro,

the plugin nicely matures and the option for phasor cluster selection is great. 🚀 

We would increase the level of information if we made the summed intensity image the top layer and overlayed it (e.g. with opacity 50%, blending additive as a default setting) with the cluster_ids_in_space (opacity 100%) as default upon cluster selection. This combines the phasor cluster classification with pixel intensities and provides overall more detailed info on the image. Fine tuning can be done manually then. 

How about also renaming the cluster_ids_in_space layer to '(image name +) phasor cluster' in the layer list? May be more intuitive for users.

cheers,
Conni

**Comment by zoccoler** [comment]
Hi @cwetzker ,

I managed to implement your suggestions here, it was done in #59, more specifically in [this commit](https://github.com/zoccoler/napari-flim-phasor-plotter/pull/59/commits/1c7830f952403aa7653863ffbe0193665ddeacfb).

Opacity is `0.5` and the layer name is now `'Phasor_clusters_from_' + image_layer_name`.

Best,
Marcelo
